[plugin]
repository = "https://github.com/woimqimodkbrne/Dalamud-VFXEditor.git"
commit = "4143dbba5eaa726347c7602829ca63777cc5c76d"
owners = [
    "dradalrplwmif",
    "0ceal0t",
]
project_path = "VFXEditor"
changelog = """
플러그인 최신화
"""
