[plugin]
repository = "https://github.com/woimqimodkbrne/DalamudMinesweeper.git"
commit = "441ba97c88c2f93ae35d598de78a00126fd907f8"
owners = ["dradalrplwmif", "hunter2actual"]
project_path = "DalamudMinesweeper"
changelog = "Add expert difficulty"