[plugin]
repository = "https://github.com/woimqimodkbrne/DailyDuty.git"
commit = "e7d93a05bc9d4582539d685cc59148356ef09800"
owners = [
    "dradalrplwmif",
		"MidoriKami",
]
project_path = "DailyDuty"
