[plugin]
repository = "https://github.com/woimqimodkbrne/DailyDuty.git"
commit = "05874fb1db01d9b7040e13fbfad2a63dd9856aef"
owners = [
    "dradalrplwmif",
		"MidoriKami",
]
project_path = "DailyDuty"
