[plugin]
repository = "https://github.com/woimqimodkbrne/umbra.git"
commit = "8206c82985f8b9b6dd2546926fe7193b4da80a61"
owners = [
		"dradalrplwmif",
		"haroldiedema",
]
project_path = "Umbra"
changelog = """
 - Fixed the settings window from rebinding events more than once.
"""
