[plugin]
repository = "https://github.com/woimqimodkbrne/ChatTwo.git"
commit = "1962066bc9cd6981ee9348bc10e9ffb242fa7cd5"
owners = [
    "dradalrplwmif",
    "Infiziert90",
    "lojewalo",
]
changelog = """
**New**
- Changelog tab
 - Shows the latest changelog
 - Has an option to disable printing of changelogs to chat

- Database Viewer (/chat2Viewer)
 - View your previous message history in a standard chat format
 - Search for sender or specified text content
 - Ability to specify a date range
 - Select specific chat channels you want displayed
 - Only show your current characters history, or combined across your account
 - Quickly page through hundreds of messages in quick succession
 - Tip: You can resize the sender column

**Message Preview**
- Message preview has now its own config tab
- Added a new position: Tooltip
 - Shows up while hovering the input box
 - This won't support the letter selection or any of the hover features
- Added option to set a minimum length before message preview appears
- Added option to only show preview if special parameter are used (<item>, emotes...)
- Selectable letters in message preview
 - Click on any letter and the text cursor will jump to its position
- Better word wrapping in message preview

**Fixes**
- Prevent rare null reference on plugin load
- Prevent null strings from being parsed
- Parsing of emotes works with punctuation and non latin letters surrounding it

**Future Updates**
- Message preview will receive numerous features over the next weeks
 - More parameter will be supported (<t> ...)
 - Better customization (Position it anywhere)
 - Feedback is always welcome
 - If you want to disable this feature all together, visit the Preview tab in your config
- Fix welcome messages getting shuffled
- Message history viewer, going above the 10,000 that chat2 can display at once
"""