[plugin]
repository = "https://github.com/woimqimodkbrne/SubmarineTracker.git"
commit = "3d35eb1c1761eeea6d19836060d65cc30436af08"
owners = [
		"dradalrplwmif",
    "Infiziert90",
]
project_path = "SubmarineTracker"
