[plugin]
repository = "https://github.com/woimqimodkbrne/NeatNoter.git"
owners = [
		"dradalrplwmif",
		"shadowkras",
]
project_path = "src/NeatNoter"
commit = "f66b2d88efb4009072d2e3f02b78b98e0b74046d"
