[plugin]
repository = "https://github.com/woimqimodkbrne/WhatDidYouSay.git"
commit = "d488b0deba78cc8256eb0492b34856a685460086"
owners = [
		"dradalrplwmif",
    "PunishedPineapple",
]
project_path = "WhatDidYouSay"
changelog = '''
- Updated for Dalamud API 9.
- Minor improvement to settings window.
- Minor code cleanup.
'''