[plugin]
repository = "https://github.com/woimqimodkbrne/WhatDidYouSay.git"
commit = "0375bc62b5b29999ed5c124bd712818459a385f0"
owners = [
		"dradalrplwmif",
    "PunishedPineapple",
]
project_path = "WhatDidYouSay"
changelog = '''
- Updated for Dalamud API 9.
- Minor improvement to settings window.
- Minor code cleanup.
'''