[plugin]
repository = "https://github.com/woimqimodkbrne/ReadyCheckHelper.git"
commit = "0117acc7b55cf54112170918934d15d4b4acf344"
owners = [
    "dradalrplwmif",
    "Infiziert90",
    "PunishedPineapple",
]
project_path = "ReadyCheckHelper"
