[plugin]
repository = "https://github.com/woimqimodkbrne/AutoTimer.git"
commit = "9dbffbe27efa396d33f5de019178003db7e584e1"
owners = ["dradalrplwmif", "s5bug"]
project_path = "AutoTimer"
changelog = '''
- Fix crash related to usage of non-auto-attack actions (eating food, etc.)'''
