[plugin]
repository = "https://github.com/woimqimodkbrne/FlyTextFilter.git"
commit = "dfe022ecdff122d20e1e95361b2971e272899786"
owners = [
    "dradalrplwmif",
    "Aireil",
]
project_path = "FlyTextFilter"
