[plugin]
repository = "https://github.com/woimqimodkbrne/EldenRingDalamud.git"
commit = "a1935fe5d718bd055a8ffcd3e0981ea7587c53fc"
owners = [
  "dradalrplwmif",
	"Roselyyn", 
	"reiichi001"
]
project_path = "EldenRing"
changelog = """
Updated for API 9 Compatibility
- Switch from opcode to dutystate by MidoriKami
- Other API 9 update grabbed from Kurochi51's PR
- Moved to stable because it was formerly testing exclusive, but didn't need to be.
"""