[plugin]
repository = "https://github.com/woimqimodkbrne/XIVComboPlugin.git"

# The commit to check out and build from the repository.
commit = "f3b33a2a67e9bc57b23332160475561c93d1f7ae"

# The people authorised to update this manifest (e.g. who can deploy updates). These are GitHub usernames.
owners = [
		"dradalrplwmif",
    "attickdoor",
]

# Optional: where your project/csproj is located within the repository.
# If empty or unspecified, it will be assumed the project is in the root of the repository.
project_path = "XIVComboPlugin"

# The changelog for this version. Will be shown in-game, as well on the Goat Place Discord.
changelog = """\
		6.5
		"""
