[plugin]
repository = "https://github.com/woimqimodkbrne/HuntBuddy.git"
owners = [ "dradalrplwmif", "SheepGoMeh", "PrincessRTFM",]
project_path = "HuntBuddy"
commit = "304511a096ff11d26b827f497b408d7276a17b8a"
changelog = "- New IPC integration\n- Main window now maintains size between restarts\n- Plugin now directly warns users about unsupported hunts (ARR and all B-ranks)\n- Now on .net8!"
