[plugin]
repository = "https://github.com/woimqimodkbrne/EurekaHelper.git"
commit = "2c90a1e74b46c8e4ad6ad4533994ba0363a6a3a9"
owners = ["dradalrplwmif", "snorux"]
project_path = "EurekaHelper"
changelog = """
Elemental Manager
- Added crowdsourced positions

Misc
- Updated to API 9
"""