[plugin]
repository = "https://github.com/woimqimodkbrne/EurekaHelper.git"
commit = "5fecef363a1d818dc40245abb54124ecdcd80350"
owners = ["dradalrplwmif", "snorux"]
project_path = "EurekaHelper"
changelog = """
- 일부 한글화
"""