[plugin]
repository = "https://github.com/woimqimodkbrne/PetScale.git"
commit = "7054d76edd1d435f18b9591ca4283fb5bef77b12"
owners = [
		"dradalrplwmif",
		"Kurochi51",
]
project_path = "PetScale"
changelog = """
- Fixed broken filter
- Possible fix for expanding dropdown
"""
