[plugin]
repository = "https://github.com/woimqimodkbrne/ChillFrames.git"
commit = "bb47c1085f44a4039ea2fd17d41138c92c9ea2ed"
owners = [
    "dradalrplwmif",
		"MidoriKami",
]
project_path = "ChillFrames"