[plugin]
repository = "https://github.com/woimqimodkbrne/BetterMountRoulette.git"
commit = "b0a2c9a556572d54b7acdfce67a5600cd482efc1"
version = "1.3.0.15"
owners = ["dradalrplwmif", "CMDRNuffin"]
changelog = """Now includes an option to only mount single-seated mounts while solo.

Also added an option to only use mounts that can fit the entire party, or failing that, as many party members as possible."""
