[plugin]
repository = "https://github.com/woimqimodkbrne/OrchestrionPlugin.git"
commit = "bb51e67a9f25cfbb2d08842bee93ea9962ca2225"
owners = [
    "dradalrplwmif",
    "lmcintyre",
]
project_path = "Orchestrion"
