[plugin]
repository = "https://github.com/woimqimodkbrne/OrchestrionPlugin.git"
commit = "53b0834cb574fc8256c4313a4cd9ba1322c6a5a1"
owners = [
    "dradalrplwmif",
    "lmcintyre",
]
project_path = "Orchestrion"
