[plugin]
repository = "https://github.com/woimqimodkbrne/OrchestrionPlugin.git"
commit = "a6bd039d5b4956a710e1eaa117654ba650a8f279"
owners = [
    "dradalrplwmif",
    "lmcintyre",
]
project_path = "Orchestrion"
